## Importing and Organizing Your Data in Python - Part II

In [3]:
from pandas_datareader import data as wb
import yfinance as yf
F = yf.download('F', start='2015-1-1')
F

C:\Users\Admin\AppData\Local\Temp\ipykernel_30300\3918217661.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  F = yf.download('F', start='2015-1-1')
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker              F          F          F          F          F
Date
2015-01-02   8.626945   8.789824   8.525849   8.756125   24777900
2015-01-05   8.289954   8.497765   8.250638   8.492148   44079700
2015-01-06   8.211322   8.368584   8.076526   8.357351   32981600
2015-01-07   8.447216   8.475299   8.295571   8.301187   26065300
2015-01-08   8.660644   8.694342   8.553930   8.649410   33943400
...               ...        ...        ...        ...        ...
2025-10-23  12.340000  12.490000  12.190000  12.470000  479840300
2025-10-24  13.840000  13.970000  12.710000  12.730000  298366900
2025-10-27  13.260000  13.800000  13.210000  13.800000  140859000
2025-10-28  13.130000  13.280000  13.040000  13.240000   96738500
2025-10-29  13.240000  13.390000  13.070000  13.100000  127404100

[2723 rows x 5 columns]

Use the “info” method to obtain basic statistics, regarding the data you extracted in the previous exercise (data from Morningstar for Ford starting from the 1st of January 2005 until today).

In [4]:
F.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2723 entries, 2015-01-02 to 2025-10-29
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   (Close, F)   2723 non-null   float64
 1   (High, F)    2723 non-null   float64
 2   (Low, F)     2723 non-null   float64
 3   (Open, F)    2723 non-null   float64
 4   (Volume, F)  2723 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 127.6 KB

Apply the “head” and “tail” methods and observe the output. How would you interpret the adjusted closing prices?

In [5]:
F.head()

Price          Close      High       Low      Open    Volume
Ticker             F         F         F         F         F
Date
2015-01-02  8.626945  8.789824  8.525849  8.756125  24777900
2015-01-05  8.289954  8.497765  8.250638  8.492148  44079700
2015-01-06  8.211322  8.368584  8.076526  8.357351  32981600
2015-01-07  8.447216  8.475299  8.295571  8.301187  26065300
2015-01-08  8.660644  8.694342  8.553930  8.649410  33943400

In [6]:
F.tail()

Price       Close   High    Low   Open     Volume
Ticker          F      F      F      F          F
Date
2025-10-23  12.34  12.49  12.19  12.47  479840300
2025-10-24  13.84  13.97  12.71  12.73  298366900
2025-10-27  13.26  13.80  13.21  13.80  140859000
2025-10-28  13.13  13.28  13.04  13.24   96738500
2025-10-29  13.24  13.39  13.07  13.10  127404100

In [7]:
F.head(20)

Price          Close      High       Low      Open    Volume
Ticker             F         F         F         F         F
Date
2015-01-02  8.626945  8.789824  8.525849  8.756125  24777900
2015-01-05  8.289954  8.497765  8.250638  8.492148  44079700
2015-01-06  8.211322  8.368584  8.076526  8.357351  32981600
2015-01-07  8.447216  8.475299  8.295571  8.301187  26065300
2015-01-08  8.660644  8.694342  8.553930  8.649410  33943400
2015-01-09  8.542694  8.688723  8.458447  8.683107  23420800
2015-01-12  8.548312  8.604477  8.486530  8.598861  22750800
2015-01-13  8.542694  8.694339  8.469680  8.638175  26279400
2015-01-14  8.486529  8.514612  8.329268  8.464063  36798300
2015-01-15  8.346116  8.514611  8.312417  8.492145  24981300
2015-01-16  8.435985  8.447217  8.284339  8.318038  32089900
2015-01-20  8.430368  8.497766  8.284339  8.469684  28553700
2015-01-21  8.407899  8.486530  8.357350  8.413515  23281500
2015-01-22  8.441597  8.464063  8.368582  8.430364  23669200
2015-01-23  8.374200  8.469680  8.362967  8.435982  21620600
2015-01-26  8.469683  8.508998  8.407901  8.413517  25237200
2015-01-27  8.340502  8.419132  8.267487  8.402283  34609100
2015-01-28  8.204330  8.414261  8.181635  8.414261  40579800
2015-01-29  8.425609  8.488020  8.113549  8.295111  40731100
2015-01-30  8.346176  8.448305  8.300786  8.368871  30439700

In [8]:
F.tail(20)

Price       Close   High    Low   Open     Volume
Ticker          F      F      F      F          F
Date
2025-10-02  12.22  12.43  12.12  12.28   74530500
2025-10-03  12.67  12.67  12.20  12.25  100778600
2025-10-06  12.70  12.80  12.48  12.63   90544900
2025-10-07  11.92  12.53  11.74  12.50  154390200
2025-10-08  11.74  12.01  11.68  11.98   78469700
2025-10-09  11.50  11.77  11.48  11.75   70320500
2025-10-10  11.41  11.59  11.35  11.55   84595400
2025-10-13  11.54  11.63  11.46  11.49   73939400
2025-10-14  11.65  11.76  11.34  11.38   89117900
2025-10-15  11.76  11.78  11.64  11.68   88960700
2025-10-16  11.74  11.79  11.64  11.74  108701200
2025-10-17  11.92  12.01  11.72  11.74  107633500
2025-10-20  11.99  12.08  11.91  11.93   77878900
2025-10-21  12.56  12.63  12.07  12.26  297153200
2025-10-22  12.43  12.60  12.28  12.53  415062200
2025-10-23  12.34  12.49  12.19  12.47  479840300
2025-10-24  13.84  13.97  12.71  12.73  298366900
2025-10-27  13.26  13.80  13.21  13.80  140859000
2025-10-28  13.13  13.28  13.04  13.24   96738500
2025-10-29  13.24  13.39  13.07  13.10  127404100

Practice extracting closing price data from the same source and for the same timeframe. Do this for Apple, Microsoft, Exxon, and British Petroleum. 
Use IEX to find the tickers of these companies, if you don’t already know them.

In [9]:
import pandas as pd
import yfinance as yf

In [11]:
tickers = ['AAPL', 'MSFT', 'XOM', 'BP']
new_data = pd.DataFrame()
for t in tickers:
    new_data[t] = yf.download(t, start='2015-1-1')['Close']

C:\Users\Admin\AppData\Local\Temp\ipykernel_30300\4180217433.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  new_data[t] = yf.download(t, start='2015-1-1')['Close']
[*********************100%***********************]  1 of 1 completed
C:\Users\Admin\AppData\Local\Temp\ipykernel_30300\4180217433.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  new_data[t] = yf.download(t, start='2015-1-1')['Close']
[*********************100%***********************]  1 of 1 completed
C:\Users\Admin\AppData\Local\Temp\ipykernel_30300\4180217433.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  new_data[t] = yf.download(t, start='2015-1-1')['Close']
[*********************100%***********************]  1 of 1 completed
C:\Users\Admin\AppData\Local\Temp\ipykernel_30300\4180217433.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  new_data[t] = yf.download(t, start='2015-1-1')['Close']
[*********************100%***********************]  1 of 1 completed

In [12]:
new_data.tail()

                  AAPL        MSFT         XOM         BP
Date
2025-10-23  259.579987  520.559998  115.980003  35.000000
2025-10-24  262.820007  523.609985  115.389999  34.540001
2025-10-27  268.809998  531.520020  115.940002  34.770000
2025-10-28  269.000000  542.070007  115.029999  34.459999
2025-10-29  269.700012  541.549988  116.449997  35.200001

In [13]:
new_data.head()

                 AAPL       MSFT        XOM         BP
Date
2015-01-02  24.261049  39.933060  58.423508  20.229773
2015-01-05  23.577578  39.565830  56.824894  19.157789
2015-01-06  23.579798  38.985107  56.522797  19.014503
2015-01-07  23.910435  39.480434  57.095535  19.062265
2015-01-08  24.829130  40.641888  58.045856  19.492121

***

Repeat this exercise for any stock of interest to you. :)