## Simpler Returns - Part I

Download the data for Microsoft (‘MSFT’) from Yahoo Finance for the period ‘2000-1-1’ until today.

In [3]:
import numpy as np
from pandas_datareader import data as wb
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
MSFT = yf.download('MSFT', start='2000-01-01', end='2025-10-29')
MSFT

C:\Users\Admin\AppData\Local\Temp\ipykernel_2988\1450641422.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  MSFT = yf.download('MSFT', start='2000-01-01', end='2025-10-29')
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2000-01-03   35.668083   36.299207   34.271960   35.916708  53228400
2000-01-04   34.463211   35.840210   34.348461   34.750086  54119000
2000-01-05   34.826584   35.610708   33.468710   34.004210  64059600
2000-01-06   33.659950   34.845699   33.162701   34.329324  54976600
2000-01-07   34.099842   34.348467   32.837593   33.239218  62013600
...                ...         ...         ...         ...       ...
2025-10-22  520.539978  525.229980  517.710022  521.150024  18962700
2025-10-23  520.559998  523.950012  518.609985  522.460022  14023500
2025-10-24  523.609985  525.349976  520.710022  522.789978  15532400
2025-10-27  531.520020  534.580017  529.010010  531.780029  18734700
2025-10-28  542.070007  553.719971  540.770020  550.000000  29986700

[6495 rows x 5 columns]

Apply the .**head()** and **.tail()** methods to check if the data is ok. Always pay attention to the dates. Try to get an idea about how the stock price changed during the period.

In [5]:
MSFT.head()

Price           Close       High        Low       Open    Volume
Ticker           MSFT       MSFT       MSFT       MSFT      MSFT
Date
2000-01-03  35.668083  36.299207  34.271960  35.916708  53228400
2000-01-04  34.463211  35.840210  34.348461  34.750086  54119000
2000-01-05  34.826584  35.610708  33.468710  34.004210  64059600
2000-01-06  33.659950  34.845699  33.162701  34.329324  54976600
2000-01-07  34.099842  34.348467  32.837593  33.239218  62013600

In [6]:
MSFT.tail()

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2025-10-22  520.539978  525.229980  517.710022  521.150024  18962700
2025-10-23  520.559998  523.950012  518.609985  522.460022  14023500
2025-10-24  523.609985  525.349976  520.710022  522.789978  15532400
2025-10-27  531.520020  534.580017  529.010010  531.780029  18734700
2025-10-28  542.070007  553.719971  540.770020  550.000000  29986700

### Simple Rate of Return

Calculate the simple returns of ‘MSFT’ for the given timeframe.

$$
\frac{P_1 - P_0}{P_0} = \frac{P_1}{P_0} - 1
$$

In [11]:
MSFT['simple_return'] = (MSFT['Close'] / MSFT['Close'].shift(1)) - 1
print (MSFT['simple_return'])

Date
2000-01-03         NaN
2000-01-04   -0.033780
2000-01-05    0.010544
2000-01-06   -0.033498
2000-01-07    0.013069
                ...
2025-10-22    0.005564
2025-10-23    0.000038
2025-10-24    0.005859
2025-10-27    0.015107
2025-10-28    0.019849
Name: simple_return, Length: 6495, dtype: float64